CREATE DATABASE IF NOT EXISTS kcal_calculator;

USE kcal_calculator;

CREATE TABLE IF NOT EXISTS foods (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    calories INT NOT NULL
);

INSERT INTO foods (name, calories)
VALUES 
    ('Apple', 52),
    ('Banana', 89),
    ('Orange', 47),
    ('Strawberry', 32),
    ('Grapes', 69),
    ('Watermelon', 30),
    ('Blueberry', 57),
    ('Pineapple', 50),
    ('Mango', 60),
    ('Peach', 39),
    ('Cherry', 50),
    ('Pear', 57),
    ('Plum', 46),
    ('Kiwi', 61),
    ('Papaya', 43),
    ('Lemon', 29),
    ('Lime', 30),
    ('Avocado', 160),
    ('Tomato', 18),
    ('Cucumber', 16),
    ('Carrot', 41),
    ('Broccoli', 34),
    ('Spinach', 23),
    ('Lettuce', 15),
    ('Potato', 77),
    ('Sweet Potato', 86),
    ('Onion', 40),
    ('Garlic', 149),
    ('Bell Pepper', 31),
    ('Zucchini', 17),
    ('Eggplant', 25),
    ('Mushroom', 22),
    ('Pumpkin', 26),
    ('Corn', 86),
    ('Peas', 81),
    ('Green Beans', 31),
    ('Asparagus', 20),
    ('Cauliflower', 25),
    ('Cabbage', 25),
    ('Brussels Sprouts', 43),
    ('Kale', 49),
    ('Celery', 16),
    ('Radish', 16),
    ('Beetroot', 43),
    ('Turnip', 28),
    ('Parsnip', 75),
    ('Rutabaga', 37),
    ('Artichoke', 47),
    ('Leek', 61),
    ('Okra', 33),
    ('Bok Choy', 13),
    ('Swiss Chard', 19),
    ('Collard Greens', 32),
    ('Mustard Greens', 27),
    ('Arugula', 25),
    ('Endive', 17),
    ('Radicchio', 23),
    ('Watercress', 11),
    ('Chicory', 23),
    ('Dandelion Greens', 45),
    ('Fennel', 31),
    ('Sorrel', 22),
    ('Taro', 142),
    ('Yam', 118),
    ('Cassava', 160),
    ('Plantain', 122),
    ('Breadfruit', 103),
    ('Jackfruit', 95),
    ('Durian', 147),
    ('Lychee', 66),
    ('Rambutan', 68),
    ('Longan', 60),
    ('Mangosteen', 73),
    ('Passion Fruit', 97),
    ('Guava', 68),
    ('Pomegranate', 83),
    ('Fig', 74),
    ('Date', 282),
    ('Raisin', 299),
    ('Prune', 240),
    ('Apricot', 48),
    ('Nectarine', 44),
    ('Persimmon', 81),
    ('Cantaloupe', 34),
    ('Honeydew', 36),
    ('Cranberry', 46),
    ('Blackberry', 43),
    ('Raspberry', 52),
    ('Gooseberry', 44),
    ('Currant', 56),
    ('Mulberry', 43),
    ('Elderberry', 73),
    ('Huckleberry', 37),
    ('Boysenberry', 50),
    ('Cloudberry', 51),
    ('Salmonberry', 47),
    ('Lingonberry', 50),
    ('Sea Buckthorn', 82),
    ('Acai Berry', 70),
    ('Maqui Berry', 65),
    ('Chicken breast', 164),
    ('Chicken thigh', 209),
    ('Chicken drumstick', 119),
    ('Chicken wing', 42),
    ('Turkey breast', 135),
    ('Turkey thigh', 161),
    ('Turkey drumstick', 119),
    ('Turkey wing', 42),
    ('Duck breast', 337),
    ('Duck thigh', 318),
    ('Duck drumstick', 119),
    ('Duck wing', 42),
    ('Goose breast', 161),
    ('Goose thigh', 161),
    ('Goose drumstick', 119),
    ('Goose wing', 42),
    ('Pork chop', 206),
    ('Pork loin', 143),
    ('Pork tenderloin', 143),
    ('Pork ribs', 172),
    ('Pork belly', 518),
    ('Pork shoulder', 212),
    ('Pork leg', 242),
    ('Beef tenderloin', 143),
    ('Beef sirloin', 143),
    ('Beef ribeye', 143),
    ('Beef striploin', 143),
    ('Beef flank', 143),
    ('Beef brisket', 143),
    ('Beef chuck', 143),
    ('Beef shank', 143),
    ('Beef round', 143),
    ('Beef short ribs', 143),
    ('Beef tongue', 143),
    ('Beef liver', 143),
    ('Beef heart', 143),
    ('Beef kidney', 143),
    ('Beef tripe', 143),
    ('Beef oxtail', 143),
    ('Beef bone marrow', 143),
    ('Lamb chop', 206),
    ('Lamb loin', 143),
    ('Lamb tenderloin', 143),
    ('Lamb ribs', 172),
    ('Lamb belly', 518),
    ('Lamb shoulder', 212),
    ('Lamb leg', 242),
    ('Venison loin', 143),
    ('Venison ribs', 172),
    ('Venison belly', 518),
    ('Venison shoulder', 212),
    ('Venison leg', 242),
    ('Rabbit loin', 143),
    ('Rabbit ribs', 172);