name: Go

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  steps:
   - name: Check out code into the Go module directory
     uses: actions/checkout@v2

   - name: Set up Go 1.x
     uses: actions/setup-go@v2
     with:
      go-version: ">=1.20.0"
     id: go

   - name: Get dependencies
     run: |
      cd backend
      go mod tidy

   - name: Build
     run: |
      cd backend
      go build -v ./...

   - name: Test
     run: |
      cd backend
      go test -v ./...
